server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  ai:
    mcp:
      server:
        name: banking-mcp
        version: 1.0.0